### ISSUE TITLE
`community.docker` collection

### ISSUE THREAD

**Issue by aartaria** [ringier-data/ops-ci-aws#13]
consider adding the `community.docker` ansible collection to the standard image.

This would allow to support e.g.

https://github.com/ringier-data/rcplus-alloy-universal-encoder/blob/8744dc46941d831f7e7636e52432bc92acaa588d/infrastructure/roles/aws-resources/tasks/sagemaker.yml#L37-L43

**Comment by zhaow-de** [comment]
Solution provided https://github.com/ringier-data/ops-ci-codebuild-image/blob/0370733452f94a28382b0e352637ce5e726337c9/app/Dockerfile#L217C13-L217C13

**Comment by zhaow-de** [comment]
Solution provided https://github.com/ringier-data/ops-ci-codebuild-image/blob/0370733452f94a28382b0e352637ce5e726337c9/app/Dockerfile#L217C13-L217C13
